### ISSUE TITLE
Install error - " No module named 'gdal' "

### ISSUE THREAD

**Issue by skampus** [SEAcoop/SE-Torino#2]
ciao, segnalo questo errore in fase di installazione.
grazie.
s.
_____________________

Impossibile caricare il plugin 'servizi_ecosistemici' a causa di un errore chiamando il metodo classFactory() 

ModuleNotFoundError: No module named 'gdal' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/11186cs/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\servizi_ecosistemici\__init__.py", line 38, in classFactory
    from .servizi_ecosistemici import ServiziEcosistemiciPlugin
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/11186cs/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\servizi_ecosistemici\servizi_ecosistemici.py", line 38, in 
    from .servizi_ecosistemici_provider import ServiziEcosistemiciProvider
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/11186cs/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\servizi_ecosistemici\servizi_ecosistemici_provider.py", line 36, in 
    from .SE_BeneficiSociali import SE_BeneficiSociali
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/11186cs/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\servizi_ecosistemici\SE_BeneficiSociali.py", line 26, in 
    import gdal
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'

Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.22.1-Białowieża Białowieża, 663dcf8fb9

**Comment by skampus** [comment]
@NyakudyaA 
for you information
